name: quehacemos_cba
description: "App de eventos culturales Córdoba - Versión cache optimizada"
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  device_info_plus: ^11.5.0
  flutter_localizations:
    sdk: flutter

  # UI y Estado
  table_calendar: ^3.0.9
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  url_launcher: ^6.3.2
  share_plus: ^11.0.0
  cached_network_image: ^3.4.1
  flutter_local_notifications: ^19.4.1
  app_badge_plus: ^1.2.3
  timezone: ^0.10.1
  flutter_dotenv: ^5.1.0
  internet_connection_checker_plus: ^2.8.0
  package_info_plus: ^9.0.0
  # Dates y localización
  intl: ^0.20.2

  # Storage local (para futuro SQLite)
  shared_preferences: ^2.0.0
  sqflite: ^2.4.2
  path: ^1.9.1
  # Firebase core (ya debe estar)
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  firebase_analytics: ^12.0.1
  firebase_messaging: ^16.0.1
  http: ^1.5.0
  # Para auth futuro (opcional ahora)
  firebase_auth: ^6.0.0
  google_sign_in: ^7.1.1
  # NUEVO: Para Apple Sign-In
  sign_in_with_apple: ^7.0.1
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - .env

# ← MOVER FUERA, al mismo nivel que flutter:
flutter_launcher_icons:
  android: false
  ios: false
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 23
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icon/app_icon.png"